### ISSUE TITLE
POAP Badge Design Template - Cedric Waxwing

### ISSUE THREAD

**Issue by cedricwaxwing** [polywrap/mini-hacks#21]
## Summary
I've created a POAP badge figma template.

## Description
Duplicate the figma file and follow the steps included to create your own POAP badge! 🕺🏽

![image](https://user-images.githubusercontent.com/80348806/145625534-b70003b5-6aaa-42cf-8089-b5aaaf3a1d84.png)

## Deliverables
https://www.figma.com/file/CvVMiexU9TRJEzin4rqjy4/Polywrap-POAP-Badge?node-id=0%3A1

## Any next steps?
I'd like to create variants for defiwrapper and polywrap.

## About you
I'm a Web3 Designer at dOrg and Polywrap, currently working on the Polyfolio project via DefiWrapper.
0x5E642f8C81DE40E7e49b6a2B606dFB94A005bC44
https://www.colinspencedesign.com

Cheers :)

**Comment by rihp** [comment]
👏 Amazing work again Colin!

Some tips from the POAP creation tool : 
> Mandatory: PNG / APNG format
> Recommended: measures 500x500px, round shape, size less than 200KB

**Comment by cedricwaxwing** [comment]
Oh sweet, thanks! I also didn't realize that you could submit apng's, which is super sweet.

**Comment by dOrgJelli** [comment]
This is so very cool @cedricwaxwing! Do you imagine there being pictures swapped out in the center, instead of having the person icon?

If so, have you thought of any cool use-cases for this!? Maybe any address that's contributed to the DAO gets one with their avatar in it?

**Comment by cedricwaxwing** [comment]
Thanks @dOrgJelli!

I really love that idea! Do you know anything about custom rendering for PNGs or how something like that might be done? I'd be super interested in tinkering on that.

**Comment by dOrgJelli** [comment]
I know that Python has a bunch of really easy to use image libraries. Could be a simple script like so (very very psuedo-code :P):
```typescript
import ImageLib from "magic-image-lib"

const topLayerPng = FileSystem.loadBytes("./top.png")
const topLayer = ImageLib.load(topLayerPng)

const bottomLayerPng = FileSystem.loadBytes("./bottom.png")
const bottomLayer = ImageLib.load(bottomLayerPng)

// This performs a "merge-layers" (think PhotoShop)
// // This can be done through alpha compositing
// // A.K.A alpha blending.
// // https://en.wikipedia.org/wiki/Alpha_compositing
const finalComposite = ImageLib.mergeLayers([
  bottomLayer, // layer 0
  topLayer       // layer 1
]);
```

The content being used must be:
```
Top Layer = your original image w/ middle man cut out
Bottom Layer = the use-case-specific image (avatar, logo, etc)
```

**Comment by cedricwaxwing** [comment]
That’s very cool. I’ve never worked with Python before, but this seems like a good project to dip  my toes into. I’ll look into it. 👍
