### ISSUE TITLE
I wrote the article "Dapps Interoperability" - CrypTod

### ISSUE THREAD

**Issue by cryptodmeme** [polywrap/mini-hacks#22]
## Summary
Raised the issue of interoperability of dapps and explained the method "polywrap" to solve it.

## Description
Last time and the time before, I was learning about polywrap. What am I impressed by? And I focused on interoperability, the missing element in web3. This is prevalent in chains, but what about dapps (SDK)? So I came up with the term "Dapps Interoperability" and proposed it. I don't know how this will spread, but I'm looking forward to it. Again, I'm hoping to bring this excitement to cryptofan's who are not developers. I considered other titles such as "Masterpiece of web3", but I decided to call it "Dapps Interoperability" in the hopes that it would generate just a little buzz.

## Deliverables
https://mirror.xyz/0x3060fd5487a9f4184dA56bA6e09F4003c204660e/AOv01gNiiBil9-QjkcVXD170anGAZetQL7-1Exup12E

## Any next steps?
I think this is the end of mini-hacks, right? Thanks for all the feedback and sharing, I really appreciate it. polywrap has helped me understand web3 better.

## About you
web3 meme dog
eth address - 0x3060fd5487a9f4184dA56bA6e09F4003c204660e
https://twitter.com/cryptodmeme

**Comment by dOrgJelli** [comment]
Hey @cryptodmeme, this is a really interesting format for an article. I appreciate the audience it's geared towards, and the direction it takes in explaining the solution.
