### ISSUE TITLE
Next Polywrap - Kevin

### ISSUE THREAD

**Issue by kev-ngo** [polywrap/mini-hacks#24]
## Summary
NextJS / Typescript template powered by Polywrap.

## Description
I wanted to build a template that had a better default config file for devs who want to build dApps with Polywrap.  Also, I noticed that a lot of Polywrap's current templates are outdated (e.g. still using old branding).

## Deliverables
Repo: [https://github.com/kev-ngo/next-polywrap](https://github.com/kev-ngo/next-polywrap)

<img width="1552" alt="1" src="https://user-images.githubusercontent.com/69411313/147691117-ee1f3228-07b2-4dbe-af90-a35c80e30ab8.png">

## Any next steps?
- Discuss with team on whether to use a config file
- Discuss where the code for the polywrap queries should live in a template
- Implement this template for other React-Polywrap bootstrapped templates

## About you
Developer and finance person

**Comment by dOrgJelli** [comment]
@kev-ngo I really like the addition of the "web3api.config.tsx" file, really interesting (and I think maybe great) developer experience. IMO it really helps from users understand that we're a middleware at the same layer in the stack as other app development tools like Next.JS. Would love to see what other devs say about this.
