### ISSUE TITLE
Wrap persistence node - Jure

### ISSUE THREAD

**Issue by nerfZael** [polywrap/mini-hacks#25]
## Summary
I created and published a Node.js console app with an integrated IPFS node that listens for ENS wrapper registrations and automatically pins the wrappers to IPFS.

## Description
One of the main drawback to IPFS is the availability of published wrappers. This projects hopes to solve that problem by allowing anyone to run a pinning node and contribute to a global wrapper persistence network. It automates the process of discovery and pinning, so that the operator does not need to have an active role in running the node.

## Deliverables
GitHub: https://github.com/nerfZael/wrap-persistence-node
NPM: https://www.npmjs.com/package/@nerfzael/wrap-persistence-node

## Any next steps?
There are a lot of potential "quality of life" changes that could/should be implemented, like: 
- Listening on more than one network
- Listen to all ENS domain registrations and get the matching ENS resolvers instead of relying on the public resolver
- Better tracking of processed domains
...

## About you
A Polywrap core dev :)

**Comment by dOrgJelli** [comment]
What an incredible project! It'd be great to continue working on this, use it as part of our infra layer, and also re-write the node's logic as Polywrappers XD

**Comment by rihp** [comment]
this sounds like an amazing solution to a prevalent problem! 👏 

we could have the dao start hosting its own wrap persistance node to have this working for everyone, right!?

**Comment by rihp** [comment]
this sounds like an amazing solution to a prevalent problem! 👏 

we could have the dao start hosting its own wrap persistance node to have this working for everyone, right!?

**Comment by nerfZael** [comment]
> this sounds like an amazing solution to a prevalent problem! clap
> 
> we could have the dao start hosting its own wrap persistance node to have this working for everyone, right!?

Already works for everyone, there's a couple of servers up running this and persisting everyone's rinkeby wrappers :)
Ofc, the more people/DAOs host it the less are the chances of all of the nodes going down
