### ISSUE TITLE
[meme'd the WEB3API] - [CrypTod]

### ISSUE THREAD

**Issue by cryptodmeme** [polywrap/mini-hacks#7]
## Summary
> I created a meme.

## Description
> Advanced products tend to be difficult for the market to understand. So we want to use meme to provide understanding and familiarity.

## Deliverables
Added on August 11 polywrap ver
![polywrap_cryptodmeme_01](https://user-images.githubusercontent.com/82617175/129098047-1bdd9b80-103d-48b9-9ea4-11b6e779c331.gif)
![polywrap_cryptodmeme_02](https://user-images.githubusercontent.com/82617175/129098069-74442bae-3fa8-4879-97bd-1472c74692ca.gif)
![polywrap_cryptodmeme_03](https://user-images.githubusercontent.com/82617175/129098090-a4a892ce-0b66-45af-8fb3-cfa363c24669.gif)
![polywrap_cryptodmeme_04](https://user-images.githubusercontent.com/82617175/129098121-6d2bac75-1227-4a8d-b843-d3d5ab27f0c3.gif)
![polywrap_cryptodmeme_05](https://user-images.githubusercontent.com/82617175/129098142-e68e7339-bc33-4a33-8ebc-0c61c27bb7c2.gif)

--

![web3api-02-calluniswap](https://user-images.githubusercontent.com/82617175/119201628-4349c400-baca-11eb-859d-53a4257a22be.gif)
source https://youtu.be/IcYHdaUx3hA
![web3api-03-comegraphql](https://user-images.githubusercontent.com/82617175/119201648-4cd32c00-baca-11eb-8839-39378c3ba244.gif)
source https://youtu.be/FERdAuQtb4A
![web3api-05-secretweapon](https://user-images.githubusercontent.com/82617175/119201686-5d83a200-baca-11eb-9658-f1ca8a726e0c.gif)
source https://youtu.be/PbHLSx5lEvc
![web3api-06-sdkwasm](https://user-images.githubusercontent.com/82617175/119201697-63798300-baca-11eb-87f5-59fb97356886.gif)
source https://youtu.be/ee925OTFBCA
![web3api-07-inwasm](https://user-images.githubusercontent.com/82617175/119962836-6997c400-bfe2-11eb-9ccd-f112279be582.gif)
source https://youtu.be/2-XxbdR3Nik
![web3api-future-road01](https://user-images.githubusercontent.com/82617175/120047449-97ffb880-c04f-11eb-9d1d-5beb1c10589e.jpg)
source https://pixabay.com/photos/road-pavement-landscape-roadway-220058/
![web3api-future-road02](https://user-images.githubusercontent.com/82617175/120047476-a51ca780-c04f-11eb-904b-65d8f621afb3.jpg)
source https://pixabay.com/photos/traffic-highway-lights-night-speed-332857/
![web3api-future-road03](https://user-images.githubusercontent.com/82617175/120047503-b5348700-c04f-11eb-99f6-ae9729bda0f2.jpg)
source https://pixabay.com/photos/hong-kong-city-traffic-lights-1990268/
source https://github.com/Web3-API/mini-hacks/issues/3
![web3api-future-road04](https://user-images.githubusercontent.com/82617175/120047556-d4331900-c04f-11eb-8aa0-155f2269dc7a.jpg)
source https://pixabay.com/photos/junction-crossing-city-night-960801/
source https://github.com/Web3-API/mini-hacks/issues/3
![web3api-future-road05](https://user-images.githubusercontent.com/82617175/120047583-e614bc00-c04f-11eb-981e-3e70e4f5dadd.jpg)

## Any next steps?
> Maybe a new meme will be created.

## About you
> My very existence is a meme. I love cryptos, blockchain and web3. I hope my favorite projects will grow.

**Comment by cryptodmeme** [comment]
Please use it to relax.

**Comment by rihp** [comment]
put ice on it

**Comment by rihp** [comment]
cause its too hot

**Comment by cryptodmeme** [comment]
0x3060fd5487a9f4184dA56bA6e09F4003c204660e
