### ISSUE TITLE
Introduction article by Frangs (discord handle: Frangs#2307) and me (discord handle: 4x4#3948)

### ISSUE THREAD

**Issue by 4x4-16** [polywrap/mini-hacks#8]
## Summary
I’ve written with the help of my friend Frangs an article on Medium to introduce people to Web3API

## Description

We’ve written this article because we see a lot of potential on Web3API and we want to make it easy for people to understand how Web3API works 

## Deliverables

https://link.medium.com/xoZJAkvA8gb

## Any next steps?

We think that this article will be very useful for people to learn about Web3API, and we plan to write more articles about Web3API for the next hacks

## About you

We are both crypto and blockchain enthusiasts who have experience on working with projects like Moonbeam

**Comment by rihp** [comment]
:fire::fire::fire::fire:

**Comment by frangsss** [comment]
0xD24DB7aD508382E5eadEc2479C499efb7Df24bb2

**Comment by 4x4-16** [comment]
0xdF840147F7719d51f229f59D6Dbd1b32744B364c
